export enum ErrorCodes {
  // music library
  INVALID_ADDED_AFTER_ERROR = 'invalid-added-after-error',
  INVALID_ADDED_BEFORE_ERROR = 'invalid-added-before-error',
  INVALID_ALBUM_ID_ERROR = 'invalid-album-id-error',
  INVALID_COVER_SIZE_ERROR = 'invalid-album-cover-size-error',
  INVALID_ARTIST_ERROR = 'invalid-artist-error',
  INVALID_ARTIST_LENGTH_ERROR = 'invalid-artist-length-error',
  INVALID_COMPOSER_ERROR = 'invalid-composer-error',
  INVALID_COMPOSER_LENGTH_ERROR = 'invalid-composer-length-error',
  INVALID_FILTER_ERROR = 'invalid-filter-error',
  INVALID_FILTER_LENGTH_ERROR = 'invalid-filter-length-error',
  INVALID_GENRE_ERROR = 'invalid-genre-error',
  INVALID_GENRE_LENGTH_ERROR = 'invalid-genre-length-error',
  INVALID_MAX_RATING_ERROR = 'invalid-max-rating-error',
  INVALID_MIN_RATING_ERROR = 'invalid-min-rating-error',
  INVALID_RELEASED_AFTER_ERROR = 'invalid-released-after-error',
  INVALID_RELEASED_BEFORE_ERROR = 'invalid-released-before-error',
  INVALID_SORT_FIELD_ERROR = 'invalid-sort-field-error',
  INVALID_SORT_ORDER_ERROR = 'invalid-sort-order-error',
  INVALID_YEAR_ERROR = 'invalid-year-error',
  // input validation errors
  INVALID_ACCOUNT_ERROR = 'invalid-account-error',
  INVALID_ENABLED_ERROR = 'invalid-enabled-error',
  INVALID_ENDED_AT_ERROR = 'invalid-ended-at-error',
  INVALID_EXPIRES_AT_ERROR = 'invalid-expires-at-error',
  INVALID_EXPIRES_AT_RANGE_ERROR = 'invalid-expires-at-range-error',
  INVALID_PASSWORD_ERROR = 'invalid-password-error',
  INVALID_PASSWORD_LENGTH_ERROR = 'invalid-password-length-error',
  INVALID_ROOT_PATH_ERROR = 'invalid-root-path-error',
  INVALID_SEARCH_LENGTH_ERROR = 'invalid-search-length-error',
  INVALID_USERNAME_ERROR = 'invalid-username-error',
  INVALID_USERNAME_LENGTH_ERROR = 'invalid-username-length-error',
  INVALID_USERNAME_NOT_UNIQUE_ERROR = 'invalid-username-not-unique-error',
  INVALID_USER_ROLE_ERROR = 'invalid-user-role-error',
  // input pagination validation errors
  INVALID_LIMIT_ERROR = 'invalid-limit-error',
  INVALID_LIMIT_RANGE_ERROR = 'invalid-limit-range-error',
  INVALID_OFFSET_ERROR = 'invalid-offset-error',
  INVALID_OFFSET_RANGE_ERROR = 'invalid-offset-range-error',
  // session and user role errors
  INVALID_JWT_TOKEN_ERROR = 'invalid-jwt-token-error',
  INVALID_ROLE_ERROR = 'invalid-role-error',
  INVALID_SESSION_ERROR = 'invalid-session-error',
  INVALID_SESSION_KEY_ERROR = 'invalid-session-key-error',
  // unauthorized or invalid ID errors
  ACCOUNT_NOT_FOUND_ERROR = 'account-not-found-error',
  ACCOUNT_ONLY_ADMIN_ERROR = 'account-only-admin-error',
  ALBUM_NOT_FOUND_ERROR = 'album-not-found-error',
  FOLDER_NOT_FOUND_ERROR = 'folder-not-found-error',
  SESSION_NOT_FOUND_ERROR = 'session-not-found-error',
  ROOT_PATH_NOT_FOUND_ERROR = 'root-path-not-found-error',
  INVALID_ACCOUNT_ID_ERROR = 'invalid-account-id-error',
  INVALID_COMPOSER_ID_ERROR = 'invalid-composer-id-error',
  INVALID_FOLDER_ID_ERROR = 'invalid-folder-id-error',
  INVALID_GENRE_ID_ERROR = 'invalid-genre-id-error',
  INVALID_ROOT_PATH_ID_ERROR = 'invalid-root-path-id-error',
  INVALID_SESSION_ID_ERROR = 'invalid-session-id-error',
  // misc
  AUTHORIZATION_ERROR = 'authorization-error',
  FORBIDDEN_ERROR = 'forbidden-error',
  BAD_REQUEST_ERROR = 'bad-request-error',
  INTERNAL_SERVER_ERROR = 'internal-server-error',
  INDEXER_CONFIGURATION_NOT_FOUND_ERROR = 'indexer-configuration-not-found-error',
  SYSTEM_CONFIGURATION_NOT_FOUND_ERROR = 'system-configuration-not-found-error',
  NOT_FOUND_ERROR = 'not-found-error',
  ROOT_PATH_DOES_NOT_EXIST_ERROR = 'root-path-does-not-exist-error',
  DUPLICATE_ROOT_PATH_ERROR = 'duplicate-root-path-error',
}
