export enum ErrorCodes {
  // input validation errors
  INVALID_ACCOUNT_ERROR = 'invalid-account-error',
  INVALID_ENABLED_ERROR = 'invalid-enabled-error',
  INVALID_ENDED_AT_ERROR = 'invalid-ended-at-error',
  INVALID_EXPIRES_AT_ERROR = 'invalid-expires-at-error',
  INVALID_EXPIRES_AT_RANGE_ERROR = 'invalid-expires-at-range-error',
  INVALID_PASSWORD_ERROR = 'invalid-password-error',
  INVALID_PASSWORD_LENGTH_ERROR = 'invalid-password-length-error',
  INVALID_ROOT_PATH_ERROR = 'invalid-root-path-error',
  INVALID_SEARCH_LENGTH_ERROR = 'invalid-search-length-error',
  INVALID_USERNAME_ERROR = 'invalid-username-error',
  INVALID_USERNAME_LENGTH_ERROR = 'invalid-username-length-error',
  INVALID_USERNAME_NOT_UNIQUE_ERROR = 'invalid-username-not-unique-error',
  INVALID_USER_ROLE_ERROR = 'invalid-user-role-error',
  // input pagination validation errors
  INVALID_LIMIT_ERROR = 'invalid-limit-error',
  INVALID_LIMIT_RANGE_ERROR = 'invalid-limit-range-error',
  INVALID_OFFSET_ERROR = 'invalid-offset-error',
  INVALID_OFFSET_RANGE_ERROR = 'invalid-offset-range-error',
  // session and user role errors
  INVALID_JWT_TOKEN_ERROR = 'invalid-jwt-token-error',
  INVALID_ROLE_ERROR = 'invalid-role-error',
  INVALID_SESSION_ERROR = 'invalid-session-error',
  INVALID_SESSION_KEY_ERROR = 'invalid-session-key-error',
  // unauthorized or invalid ID errors
  ACCOUNT_NOT_FOUND_ERROR = 'account-not-found-error',
  ACCOUNT_ONLY_ADMIN_ERROR = 'account-only-admin-error',
  SESSION_NOT_FOUND_ERROR = 'session-not-found-error',
  ROOT_PATH_NOT_FOUND_ERROR = 'root-path-not-found-error',
  INVALID_ACCOUNT_ID_ERROR = 'invalid-account-id-error',
  INVALID_ROOT_PATH_ID_ERROR = 'invalid-root-path-id-error',
  INVALID_SESSION_ID_ERROR = 'invalid-session-id-error',
  // misc
  AUTHORIZATION_ERROR = 'authorization-error',
  FORBIDDEN_ERROR = 'forbidden-error',
  BAD_REQUEST_ERROR = 'bad-request-error',
  INTERNAL_SERVER_ERROR = 'internal-server-error',
  INDEXER_CONFIGURATION_NOT_FOUND_ERROR = 'indexer-configuration-not-found-error',
  SYSTEM_CONFIGURATION_NOT_FOUND_ERROR = 'system-configuration-not-found-error',
  NOT_FOUND_ERROR = 'not-found-error',
  ROOT_PATH_DOES_NOT_EXIST_ERROR = 'root-path-does-not-exist-error',
  DUPLICATE_ROOT_PATH_ERROR = 'duplicate-root-path-error',
}
