export const AUTHENTICATION_PROVIDER = 'AUTHENTICATION_PROVIDER';
export const REQUEST_THROTTLING_PROVIDER = 'REQUEST_THROTTLING_PROVIDER';
export const SEQUELIZE_PROVIDER = 'SEQUELIZE_PROVIDER';

export const ACCOUNT_ENTITY_PROVIDER = 'ACCOUNT_ENTITY_PROVIDER';
export const ACCOUNT_SERVICE_PROVIDER = 'ACCOUNT_SERVICE_PROVIDER';
export const SESSION_ENTITY_PROVIDER = 'SESSION_ENTITY_PROVIDER';
export const SESSION_SERVICE_PROVIDER = 'SESSION_SERVICE_PROVIDER';
